application: smurfomatic608
version: stasks
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /tasks
  script: tasks.py
- url: /tasks2
  script: tasks2.py
- url: /tasks2x
  script: tasks2x.py
- url: /project/.*
  script: project.py
- url: /project
  script: project.py
- url: /.*
  script: helloworld.py


